name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below to help us understand your idea.

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: "I would like soundvibes to support..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it Solves
      description: What problem does this feature solve? Or what use case does it enable?
      placeholder: "This would help me when I need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: "The CLI could add a flag like --format json that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: "I tried working around this by..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
